services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: springschoolapp
      POSTGRES_USER: bakemono
      POSTGRES_PASSWORD: bakemono
    ports:
      - "5433:5432" # Corrected port mapping (5432 is the default PostgreSQL port)
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-noisy-dawn-a5bgeovq.us-east-2.aws.neon.tech/springschoolapp?user=springschoolapp_owner&password=xryLwpqMj5h4&sslmode=require
      SPRING_DATASOURCE_USERNAME: bakemono
      SPRING_DATASOURCE_PASSWORD: bakemono

volumes:
  pgdata: {}
