spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springschool
    username: fatimata
    password: passer123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
