spring:
  datasource:
    url: jdbc:postgresql://ep-noisy-dawn-a5bgeovq.us-east-2.aws.neon.tech/springschoolapp?user=springschoolapp_owner&password=xryLwpqMj5h4&sslmode=require
    username: bakemono
    password: bakemono
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 3000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true