spring:
  datasource:
    url: jdbc:postgresql://ep-floral-tooth-a5ts3xfc.us-east-2.aws.neon.tech/spring?sslmode=require
    username: spring_owner
    password: euibO9sqS8am
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true